import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000' },
  centerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  video: { width, height: height * 0.85, alignSelf: 'center' },
  backButton: {
    position: 'absolute',
    top: 50,
    left: 20,
    backgroundColor: 'rgba(0,0,0,0.8)',
    padding: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
    zIndex: 10,
  },
  backButtonInline: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    padding: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
  },
  errorButtonRow: {
    flexDirection: 'row',
    gap: 10,
  },
  retryButton: {
    backgroundColor: 'rgba(229,9,20,0.85)',
    padding: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
  },
  episodesButton: {
    backgroundColor: 'rgba(0,0,0,0.8)',
    padding: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
  },
  topRightStack: {
    position: 'absolute',
    top: 50,
    right: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    zIndex: 10,
  },
  backText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  loadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.9)',
    zIndex: 5,
  },
  loadingText: { color: '#fff', marginTop: 10, fontSize: 14 },
  errorText: { color: '#ff6b6b', fontSize: 16, textAlign: 'center', marginBottom: 20 },
  titleContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    padding: 10,
  },
  titleText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  episodeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 50,
    paddingHorizontal: 16,
    paddingBottom: 12,
    gap: 12,
  },
  episodeHeaderTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
    flex: 1,
  },
  inlineResolving: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 12,
    gap: 8,
  },
  inlineResolvingText: {
    color: '#8e8e93',
    fontSize: 13,
  },
  episodeList: {
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  episodeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
  },
  episodeIndexBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  episodeIndexText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  episodeThumb: {
    width: 46,
    height: 66,
    borderRadius: 6,
    backgroundColor: 'rgba(255,255,255,0.08)',
    marginRight: 12,
  },
  episodeItemText: { color: '#fff', fontSize: 15, flex: 1 },
});

export default styles;